
DROP MATERIALIZED VIEW IF EXISTS mimiciii.overalltable_Lab;
CREATE MATERIALIZED VIEW mimiciii.overalltable_Lab AS

SELECT merged.subject_id, hadm_id, icustay_id, charttime 
	 ,AVG(HEMATOCRIT)AS HEMATOCRIT
	 ,AVG(PLATELET_COUNT)AS PLATELET_COUNT
	 ,AVG(HEMOGLOBIN)AS HEMOGLOBIN
	 ,AVG(MCHC)AS MCHC
	 ,AVG(RBC)AS RBC
	 ,AVG(MCH)AS MCH
	 ,AVG(MCV)AS MCV
	 ,AVG(RDW)AS RDW
	 ,AVG(PTT)AS PTT
	 ,AVG(INR)AS INR
	 ,AVG(PT)AS PT
	 ,AVG(LYMPHOCYTES)AS LYMPHOCYTES
	 ,AVG(NEUTROPHILS)AS NEUTROPHILS
	 ,AVG(MONOCYTES) AS MONOCYTES
	 ,AVG(EOSINOPHILS)AS EOSINOPHILS
	 ,AVG(BASOPHILS)AS BASOPHILS
	 ,AVG(BANDS)AS BANDS
	 ,AVG(HYPOCHROMIA)AS HYPOCHROMIA
	 ,AVG(ANISOCYTOSIS)AS ANISOCYTOSIS
	 ,AVG(MACROCYTES)AS MACROCYTES
	 ,AVG(ATYPICAL_LYMPHOCYTES)AS ATYPICAL_LYMPHOCYTES
	 ,AVG(METAMYELOCYTES)AS METAMYELOCYTES
	 ,AVG(MYELOCYTES)AS MYELOCYTES
	 ,AVG(MICROCYTES)AS MICROCYTES
	 ,AVG(POIKILOCYTOSIS)AS POIKILOCYTOSIS
	 ,AVG(POLYCHROMASIA)AS POLYCHROMASIA
	 ,AVG(FIBRINOGEN)AS FIBRINOGEN
	 ,AVG(PLATELET_SMEAR)AS PLATELET_SMEAR
	 ,AVG(GRANULOCYTE_COUNT)AS GRANULOCYTE_COUNT
	 ,AVG(NUCLEATED_RED_CELLS)AS NUCLEATED_RED_CELLS
	 ,AVG(OVALOCYTES)AS OVALOCYTES
	 ,AVG(UREA_NITROGEN)AS UREA_NITROGEN
	 ,AVG(SCHISTOCYTES)AS SCHISTOCYTES
	 ,AVG(RETICULOCYTE_COUNT)AS RETICULOCYTE_COUNT
	 ,AVG(TEARDROP_CELLS)AS TEARDROP_CELLS
	 ,AVG(BURR_CELLS)AS BURR_CELLS
	 ,AVG(SEDIMENTATION_RATE)AS SEDIMENTATION_RATE
	 ,AVG(LARGE_PLATELETS)AS LARGE_PLATELETS
	 ,AVG(TARGET_CELLS)AS TARGET_CELLS
	 ,AVG(FIBRIN_DEGRADATION_PRODUCTS)AS FIBRIN_DEGRADATION_PRODUCTS
	 ,AVG(D_DIMER)AS D_DIMER
	 ,AVG(RED_BLOOD_CELL_FRAGMENTS)AS RED_BLOOD_CELL_FRAGMENTS
	 ,AVG(BASOPHILIC_STIPPLING)AS BASOPHILIC_STIPPLING
	 ,AVG(UHOLD)AS UHOLD
	 ,AVG(BLASTS)AS BLASTS
	 ,AVG(POLYS)AS POLYS
	 ,AVG(WBC) AS WBC

FROM
(
SELECT lab.subject_id, lab.hadm_id, lab.icustay_id, lab.charttime
		--lab values 
	,HEMATOCRIT,PLATELET_COUNT,HEMOGLOBIN,MCHC,RBC,MCH,MCV,RDW,PTT,INR,PT,LYMPHOCYTES,NEUTROPHILS, MONOCYTES,EOSINOPHILS,	BASOPHILS,	BANDS,	HYPOCHROMIA,	ANISOCYTOSIS,	MACROCYTES
,	ATYPICAL_LYMPHOCYTES,	METAMYELOCYTES,	MYELOCYTES,	MICROCYTES,	POIKILOCYTOSIS,	POLYCHROMASIA,	FIBRINOGEN,	PLATELET_SMEAR,	GRANULOCYTE_COUNT,	NUCLEATED_RED_CELLS
,	OVALOCYTES,	UREA_NITROGEN,	SCHISTOCYTES,	RETICULOCYTE_COUNT,	TEARDROP_CELLS,	BURR_CELLS,	SEDIMENTATION_RATE,	LARGE_PLATELETS,	TARGET_CELLS
,	FIBRIN_DEGRADATION_PRODUCTS,	D_DIMER,	RED_BLOOD_CELL_FRAGMENTS,	BASOPHILIC_STIPPLING,	UHOLD,	BLASTS, POLYS,WBC

	FROM mimiciii.getLabvalues1 lab 
)
merged 


group by subject_id, hadm_id, icustay_id, charttime	
order by subject_id, hadm_id, icustay_id, charttime

